language: java
jdk:
  - openjdk8
  
#addons:
  #sonarcloud:
    #organization: "sanjuthomas"
    #token:
      #secure: "8a0b735a0417db0399d2e2620b7cc1d2703b7c49"
      
script:
  - mvn -DexcludeTag=integration clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar package

after_success:
  - bash <(curl -s https://codecov.io/bash)
